[tool.black]
preview = true

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]

[project]
name = "obr"
authors = [{name = "greole", email = "go@hpsim.de"}]
dynamic = ["version", "description"]

dependencies = [
	"signac==1.8.0",
	"signac-flow==0.23.0",
    Owls = { git = "https://github.com/greole/Owls.git", branch = "parser" }
]

[project.optional-dependencies]
doc = [
    "sphinx~=4.2.0",
    "sphinx-autoapi",
    "myst_parser",
]
