[project]
name = "obr"
version = "0.3.0"
description="A tool to create and run OpenFOAM parameter studies"
authors = [
    {name = "Gregor Olenik", email = "go@hpsim.de"},
]
license = {text = "BSD-2-Clause"}
requires_python=">=3.6"
keywords=[
   "OpenFOAM", "Parameter Studies", "Simulation Provisioning", "Workflow Manager"
]
readme="Readme.md"
classifiers=[
    # complete classifier list: http://pypi.python.org/pypi?%3Aaction=list_classifiers
    "License :: OSI Approved :: BSD License",
    "Operating System :: Unix",
    "Operating System :: POSIX",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Utilities",
]

dependencies = [
    "click",
    "PyYAML",
    "signac==1.8.0",
    "signac-flow==0.23.0",
    "GitPython==3.1.31",
    "pandas",
    "DeepDiff",
    "jsonschema==4.19.1",
    "Owls @ git+https://github.com/greole/Owls.git@Owls2.0"
]

dynamic = ["scripts"]

[project_urls]
Documentation= "https://obr.readthedocs.io/"
Changelog= "https://obr.readthedocs.io/en/latest/changelog.html"
Issues= "https://github.com/hpsim/obr/issues"

[project.optional-dependencies]
doc = [
    "sphinx~=4.2.0",
    "sphinx-autoapi",
    "myst_parser"
]
test = [
    "pytest",
    "coverage",
    "gitpython"
]

[tool.black]
preview = true

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]
