[project]
name = "obr"
version = "0.1.0"

dependencies = [
    "click",
    "PyYAML",
    "signac==1.8.0",
    "signac-flow==0.23.0",
    "Owls @ git+https://github.com/greole/Owls.git@Owls2.0"
]

[project.optional-dependencies]
doc = [
    "sphinx~=4.2.0",
    "sphinx-autoapi",
    "myst_parser",
    "pytest",
]

[tool.black]
preview = true

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]
