name: black-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Install dependencies for demo Python project
        run: |
          python -m pip install --upgrade pip
          pip install autoflake pytest
      - name: autoflake
        run: autoflake -r --in-place --remove-all-unused-imports   --ignore-init-module-imports --remove-unused-variables src
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Format Code"
          commit-message: ":art: Format Python code with psf/black"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This pull request
            uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/ci
on:
  issue_comment:
    types: [created]
jobs:
  format:
      name: format
      runs-on: ubuntu-latest
      if: github.event.issue.pull_request != '' && github.event.comment.body == 'format!' && (github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')
      steps:
      - name: Checkout the latest code (shallow clone)
        uses: actions/checkout@v2
      - name: run formatter
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: autoflake -r --in-place --remove-all-unused-imports   --ignore-init-module-imports --remove-unused-variables src
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Changes formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Code Formatting due to format! PR-comment
