name: black-action
on: [push, pull_request]
jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for demo Python project
        if: always()
        run: |
          python -m pip install --upgrade pip
          pip install autoflake pytest
      - uses: psf/black@stable
        with:
          version: "23.12.1"
          options: ". --check"
      - name: autoflake
        if: always()
        run: |
          autoflake -r  --remove-all-unused-imports   --ignore-init-module-imports --remove-unused-variables src
          autoflake -rc  --remove-all-unused-imports   --ignore-init-module-imports --remove-unused-variables src
