name: Tests

on:
  - push
  - pull_request

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest tox tox-gh-actions coverage
    - name: Install package
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        coverage run -m pytest -m "not integtest"
        coverage report

    - name: Get total coverage
      run: |
        export TOTAL=$(coverage report|tail -n 1|grep --only-matching "[0-9]*\%"|grep --only-matching "[0-9]*")
        echo $TOTAL
        echo "COVERAGE=$TOTAL" >> $GITHUB_ENV

    - name: "Make coverage badge"
      uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        # GIST_TOKEN is a GitHub personal access token with scope "gist".
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: 70b77e941a906fc3863661697ea8e864   # replace with your real Gist id.
        filename: covbadge.json
        label: Coverage
        message: ${{ env.COVERAGE }}%
        minColorRange: 50
        maxColorRange: 90
        valColorRange: ${{ env.COVERAGE }}

  integration-test:
    runs-on: ubuntu-latest
    container: greole/ofbase

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update
        apt install -y pip
        python3 -m pip install --upgrade pip

    - name: Install package
      run: |
        python3 -m pip install .

    - name: Test with pytest
      run: |
        export FOAM_ETC=/root/OpenFOAM/openfoam/etc/
        export FOAM_TUTORIALS=/root/OpenFOAM/openfoam/tutorials
        export PATH=/root/OpenFOAM/user-v2212/platforms/linux64GccDPInt32Opt/bin:/root/OpenFOAM/openfoam/site/2212/platforms/linux64GccDPInt32Opt/bin:/root/OpenFOAM/openfoam/platforms/linux64GccDPInt32Opt/bin:/root/OpenFOAM/openfoam/bin:/root/OpenFOAM/openfoam/wmake:$PATH
        export LD_LIBRARY_PATH=/root/OpenFOAM/user-v2212/platforms/linux64GccDPInt32Opt/lib:/root/OpenFOAM/openfoam/site/2212/platforms/linux64GccDPInt32Opt/lib:/root/OpenFOAM/openfoam/platforms/linux64GccDPInt32Opt/lib/sys-openmpi:/root/OpenFOAM/openfoam/platforms/linux64GccDPInt32Opt/lib:/root/OpenFOAM/openfoam/ThirdParty/platforms/linux64Gcc/fftw-3.3.10/lib64:/root/OpenFOAM/openfoam/ThirdParty/platforms/linux64Gcc/CGAL-4.14.3/lib64:/root/OpenFOAM/openfoam/ThirdParty/platforms/linux64Gcc/boost_1_74_0/lib64:/usr/lib/x86_64-linux-gnu/openmpi/lib:/root/OpenFOAM/openfoam/platforms/linux64GccDPInt32Opt/lib/dummy
        obr init --config tests/cavity.yaml
        obr run -o fetchCase
        obr run -o generate
        obr run -o runSerialSolver -t 1
