name: Tests

on:
  - push
  - pull_request

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest tox tox-gh-actions coverage setuptools
        pip install setuptools --upgrade
    - name: Install package
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        coverage run -m pytest -m "not integtest"
        coverage report

    - name: Get total coverage
      run: |
        export TOTAL=$(coverage report|tail -n 1|grep --only-matching "[0-9]*\%"|grep --only-matching "[0-9]*")
        echo $TOTAL
        echo "COVERAGE=$TOTAL" >> $GITHUB_ENV

    - name: "Make coverage badge"
      uses: schneegans/dynamic-badges-action@v1.4.0
      with:
        # GIST_TOKEN is a GitHub personal access token with scope "gist".
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: 70b77e941a906fc3863661697ea8e864   # replace with your real Gist id.
        filename: covbadge.json
        label: Coverage
        message: ${{ env.COVERAGE }}%
        minColorRange: 50
        maxColorRange: 90
        valColorRange: ${{ env.COVERAGE }}
